# Generated by Django 3.0.2 on 2020-02-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=20, verbose_name='Возраст')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Кличка')),
                ('breed', models.CharField(max_length=50, verbose_name='Порода')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('arrival_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('image', models.ImageField(blank=True, upload_to='img/%Y/%m/%d', verbose_name='Фото')),
            ],
        ),
    ]
