# Generated by Django 3.0.2 on 2020-02-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='sex',
            field=models.CharField(choices=[('m', 'Кот'), ('f', 'Кошка')], default=None, max_length=10),
        ),
    ]
