# Generated by Django 3.0.2 on 2020-02-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20200208_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default=None, max_length=10, verbose_name='Пол'),
        ),
    ]
