# Generated by Django 3.0.2 on 2020-02-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Животное', 'verbose_name_plural': 'Животные'},
        ),
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='arrival_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(upload_to='img/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='spec',
            field=models.CharField(choices=[('p', 'Попугай'), ('c', 'Кошка'), ('d', 'Собака')], default=None, max_length=10, verbose_name='Вид животного'),
        ),
    ]
