# Generated by Django 3.0.2 on 2020-02-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20200209_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Новость')),
                ('text', models.TextField(verbose_name='Текст')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(blank=True, choices=[('m', 'Мальчик'), ('f', 'Девочка')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='spec',
            field=models.CharField(blank=True, choices=[('p', 'Попугай'), ('c', 'Кошка'), ('d', 'Собака')], max_length=10, verbose_name='Вид животного'),
        ),
    ]
